[package]
name = "json-rule"
version = "0.1.0"
edition = "2021"

[dependencies]
action-system = { path = "../action-system" }
token-input = { path = "../token-input" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"