[workspace]
members = [
    "crates/action-system",
    "crates/rule-system",
    "crates/battle-core",
    "crates/ui",
]

[package]
name = "hello-bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.16.0"
rand = "0.8.5"
action-system = { path = "crates/action-system" }
rule-system = { path = "crates/rule-system" }
battle-core = { path = "crates/battle-core" }
ui = { path = "crates/ui" }

