services:
  claude-dev:
    build: .
    volumes:
      - .:/workspace
    working_dir: /workspace
    network_mode: host
    environment:
      - NODE_ENV=development
      - CARGO_BUILD_TARGET_DIR=/workspace/.claude-dev/target
      - GIT_DIR=/workspace/.claude-dev/.git
    stdin_open: true
    tty: true
    command: bash
