[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.16.0"
battle-core = { path = "../battle-core" }
action-system = { path = "../action-system" }
rule-system = { path = "../rule-system" }